RIP: feat: collapsed cadp
frmscoe/transaction-aggregation-decisioning-processor pull request #53
Opened 2023-09-14 12:26 UTC by JeanPierreNell

2023-09-18 11:21 UTC, johanfol commented on src/services/helper.service.ts
> +    span = apm.startSpan(`[${transactionID}] Delete Typology interim cache key`);
```suggestion
    span = apm.startSpan(`[${transactionID}] Delete Channel interim cache key`);
```

2023-09-18 11:35 UTC, johanfol requested changes

2023-09-18 11:35 UTC, johanfol commented on src/services/helper.service.ts
> +    const jtypologyCount = await databaseManager.addOneGetCount(cacheKey, JSON.stringify(channelResult));
This should be jChannelCount, not typology. It's misleading.

2023-09-18 11:35 UTC, johanfol commented on __tests__/unit/logic.test.ts
> +        if (message) {
bad practice to put this guard in unit tests - if someone modifies the method that returns the networkmap to return null, the tests will no longer run and not report an error / failure of the test to run. 

If you need to add the null check, at least put a throw in the "else" of the guard. That would be fine.

2023-09-18 13:17 UTC, johanfol approved these changes

2023-09-19 06:50 UTC, JeanPierreNell commented
Pulled in Protobuff changes per: https://github.com/frmscoe/General-Issues/issues/265

2023-09-19 06:51 UTC, cshezi approved these changes
🐐 ed

2023-09-19 07:41 UTC, rtkay123 approved these changes

2023-09-19 07:49 UTC, merged